### ISSUE TITLE
AttributeError: module 'tensorboard.summary._tf.summary' has no attribute 'FileWriter'

### ISSUE THREAD

**Issue by ramesh-ai** [yunjey/stargan#109]
Hi, I have tried setting up the project in my local system. But i am facing an issue with tensorboard.
============================================
The number of parameters: 44762048
Traceback (most recent call last):
  File "main.py", line 110, in <module>
    main(config)
  File "main.py", line 40, in main
    solver = Solver(celeba_loader, rafd_loader, config)
  File "/home/ubuntu/princess/StarGAN/solver.py", line 70, in __init__
    self.build_tensorboard()
  File "/home/ubuntu/princess/StarGAN/solver.py", line 109, in build_tensorboard
    self.logger = Logger(self.log_dir)
  File "/home/ubuntu/princess/StarGAN/logger.py", line 9, in __init__
    self.writer = tf.summary.FileWriter(log_dir)
AttributeError: module 'tensorboard.summary._tf.summary' has no attribute 'FileWriter'
=======================
Can you please help me out of the issue. I tried downgrading tensorboard as well as upgrade but none worked.

Thanks in advance.

**Comment by iamzhangyunlu** [comment]
try older version of tensorflow？

**Comment by ctcook97** [comment]
I changed that line to
self.writer = tf.summary.create_file_writer(log_dir)

**Comment by iamzhangyunlu** [comment]
> I changed that line to
> self.writer = tf.summary.create_file_writer(log_dir)

Does that work? I changed the version of tensorflow to 1.14.0 and the matched tensorboard version, then worked!

**Comment by globalizemeramesh** [comment]
Changing the version to 1.14.0  worked for me. Thank you so much. 
This ticket can be closed.
And i am facing an issue while testing the model too. I guess i should create a new ticket for resolution ???

**Comment by ramesh-ai** [comment]
Changing the version to 1.14.0 worked for me. Thank you so much.
This ticket can be closed.
And i am facing an issue while testing the model too. I guess i should create a new ticket for resolution ???

**Comment by iamzhangyunlu** [comment]
> Changing the version to 1.14.0 worked for me. Thank you so much.
> This ticket can be closed.
> And i am facing an issue while testing the model too. I guess i should create a new ticket for resolution ???

Have a try

**Comment by ctcook97** [comment]
@iamzhangyunlu I'm very knew to this so I can't really tell you why it worked (found it as an answer to a different question) but it worked for me

**Comment by iamzhangyunlu** [comment]
> @iamzhangyunlu I'm very knew to this so I can't really tell you why it worked (found it as an answer to a different question) but it worked for me

That's good! Congrats👍
