### ISSUE TITLE
solver.py  problem

### ISSUE THREAD

**Issue by seanyuyuyu** [yunjey/StarGAN#11]
In solver.py ，if you have no GPU, the .cuda() will be runtime error
so you must judge the torch.cuda.is_available() first 

` # Compute gradient penalty
                alpha = torch.rand(real_x.size(0), 1, 1, 1).cuda().expand_as(real_x)
                interpolated = Variable(alpha * real_x.data + (1 - alpha) * fake_x.data, requires_grad=True)
                out, out_cls = self.D(interpolated)

                grad = torch.autograd.grad(outputs=out,
                                           inputs=interpolated,
                                           grad_outputs=torch.ones(out.size()).cuda(),
                                           retain_graph=True,
                                           create_graph=True,
                                           only_inputs=True)[0]`

**Comment by ddxu** [comment]
@seanyuyuyu , hi，I have gpu on my machine, and torch.cuda.is_available() returns true. But I still meet runtine errors when call backward process of gradient penalty loss, as the sentence: **d_loss.backward()**
`
# Compute gradient penalty
                alpha = torch.rand(real_x.size(0), 1, 1, 1).cuda().expand_as(real_x)
                interpolated = Variable(alpha * real_x.data + (1 - alpha) * fake_x.data, requires_grad=True)
                out, out_cls = self.D(interpolated)

                grad = torch.autograd.grad(outputs=out,
                                           inputs=interpolated,
                                           grad_outputs=torch.ones(out.size()).cuda(),
                                           retain_graph=True,
                                           create_graph=True,
                                           only_inputs=True)[0]

                grad = grad.view(grad.size(0), -1)
                grad_l2norm = torch.sqrt(torch.sum(grad ** 2, dim=1))
                d_loss_gp = torch.mean((grad_l2norm - 1)**2)

                # Backward + Optimize
                d_loss = self.lambda_gp * d_loss_gp
                self.reset_grad()
                d_loss.backward()
                self.d_optimizer.step()
`
**err info as follows:**
Traceback (most recent call last):
  File "/home/xxxx/StarGAN-master/main.py", line 122, in <module>
    main(config)
  File "/home/xxxx/StarGAN-master/main.py", line 43, in main
    solver.train()
  File "/home/xxxx/StarGAN-master/solver.py", line 317, in train
    d_loss.backward()
  File "/home/xxxx/anaconda2/lib/python2.7/site-packages/torch/autograd/variable.py", line 167, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, retain_variables)
  File "/home/xxxx/anaconda2/lib/python2.7/site-packages/torch/autograd/__init__.py", line 99, in backward
    variables, grad_variables, retain_graph)
RuntimeError: undefined Tensor

**Comment by ddxu** [comment]
Update pytorch to 0.4.0a0+33bb849 solved this problem.

**Comment by yunjey** [comment]
Sorry for late reply. We fixed this issue now.
