### ISSUE TITLE
AssertionError: MaskedFill can't differentiate the mask

### ISSUE THREAD

**Issue by viekie** [yunjey/StarGAN#12]
hi, when i run the following command , i get a exception, can you help  me?
@yunjey 

python3 main.py --mode='train' --dataset='CelebA' --c_dim=5 --image_size=128 --sample_path='stargan_celebA/samples' --log_path='stargan_celebA/logs' --model_save_path='stargan_celebA/models' --result_path='stargan_celebA/results'

The number of parameters: 44762048
Traceback (most recent call last):
  File "main.py", line 106, in <module>
    main(config)
  File "main.py", line 41, in main
    solver.train()
  File "/data1/software/deeplearning/StarGAN/solver.py", line 279, in train
    accuracies = self.compute_accuracy(out_cls, real_label, self.dataset)
  File "/data1/software/deeplearning/StarGAN/solver.py", line 145, in compute_accuracy
    predicted = self.threshold(x)
  File "/data1/software/deeplearning/StarGAN/solver.py", line 138, in threshold
    x[x >= 0.5] = 1
  File "/usr/local/lib/python3.5/dist-packages/torch/autograd/variable.py", line 85, in __setitem__
    return MaskedFill.apply(self, key, value, True)
  File "/usr/local/lib/python3.5/dist-packages/torch/autograd/_functions/tensor.py", line 440, in forward
    assert not ctx.needs_input_grad[1], "MaskedFill can't differentiate the mask"
AssertionError: MaskedFill can't differentiate the mask

**Comment by mrlzla** [comment]
change lines of the method as follows:
```
x = (x >= 0.5).float()
```

**Comment by viekie** [comment]
@mrlzla thank you! it's a bug of pytorch in version 0.3. when i switch to pytorch 0.2,  everything runs well!!!!

**Comment by andropar** [comment]
@mrlzla Could you expand on your answer? What lines of what method do I have to change?

**Comment by SummerHuiZhang** [comment]
Yes!Thank you so much. In detail,
two lines in solver.py change from
" x[x >= 0.5] = 1
 x[x < 0.5] = 0"
     TO:  
"x = (x >= 0.5).float()
 x = (x < 0.5).float()"

**Comment by yunjey** [comment]
@mrlzla Thanks a lot. I changed the code of this repo :)
@SummerHuiZhang  You should not add the code "x = (x < 0.5).float()".

**Comment by Solacex** [comment]
well,  you could just use torch.clamp(x , 0, 0.5) to limit the x in the range (0, 0.5)
