### ISSUE TITLE
Dataset link is not working

### ISSUE THREAD

**Issue by ErfanMoosaviMonazzah** [yunjey/StarGAN#141]
Hi, when I open the following link from download.sh, its not working, 404 error is shown.
https://www.dropbox.com/s/d1kjpkqklf0uw77/celeba.zip?dl=0
Is there a new link to download the data?

**Comment by tobuta** [comment]
Hi, you can download celebA data set by changing the .sh code like this:

if [ $FILE == "celeba" ]; then

    # CelebA images and attribute labels
    URL=https://drive.google.com/uc?id=0B7EVK8r0v71pZjFTYXZWM3FlRnM
    ZIP_FILE=./data/celeba.zip
    mkdir -p ./data/
    gdwon $URL -O $ZIP_FILE
    unzip $ZIP_FILE -d ./data/
    rm $ZIP_FILE

Don`t forget to 'pip install gdown', hope this will help you^^.

**Comment by ErfanMoosaviMonazzah** [comment]
Thanks, that worked.
