### ISSUE TITLE
Question about the method

### ISSUE THREAD

**Issue by dougsouza** [yunjey/StarGAN#18]
Congratulations. Impressive results!! After reading the paper I still didn't understand completely some aspects. For example, there is no noise input for the generator? Is it possible to generate an image from latent space like a regular GAN?

Thanks!!

**Comment by yunjey** [comment]
No, it can't. StarGAN is an image-to-image translation model, such as pix2pix and CycleGAN, which does not utilize latent vectors in training phase.
