### ISSUE TITLE
RuntimeError: dimension out of range

### ISSUE THREAD

**Issue by rAm1n** [yunjey/StarGAN#24]
Hi,

I am trying to train the model on RaFD using python3 and torch v3. I've already prepared the dataset but after one epoch, this is what I am getting.  Can someone please help me solve this?

I printed the size of out_cls, real_label.

I also tried training on CelebA+RaFD but I got cuda memory error. My gpu has only 8Gb of memory space ( I have two of them). Any workaround?

Thanks!

> D
Discriminator(
  (main): Sequential(
    (0): Conv2d (3, 64, kernel_size=(4, 4), stride=(2, 2), padding=(1, 1))
    (1): LeakyReLU(0.01, inplace)
    (2): Conv2d (64, 128, kernel_size=(4, 4), stride=(2, 2), padding=(1, 1))
    (3): LeakyReLU(0.01, inplace)
    (4): Conv2d (128, 256, kernel_size=(4, 4), stride=(2, 2), padding=(1, 1))
    (5): LeakyReLU(0.01, inplace)
    (6): Conv2d (256, 512, kernel_size=(4, 4), stride=(2, 2), padding=(1, 1))
    (7): LeakyReLU(0.01, inplace)
    (8): Conv2d (512, 1024, kernel_size=(4, 4), stride=(2, 2), padding=(1, 1))
    (9): LeakyReLU(0.01, inplace)
    (10): Conv2d (1024, 2048, kernel_size=(4, 4), stride=(2, 2), padding=(1, 1))
    (11): LeakyReLU(0.01, inplace)
  )
  (conv1): Conv2d (2048, 1, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
  (conv2): Conv2d (2048, 8, kernel_size=(2, 2), stride=(1, 1), bias=False)
)
The number of parameters: 44786624
Classification Acc (8 emotional expressions):  ['12.50']

> Elapsed

> Classification Acc (8 emotional expressions):  ['12.50']
> Elapsed [0:00:04.683473], Epoch [1/200], Iter [10/31], G/loss_cls: 2.1469, G/loss_rec: 0.6333, D/loss_fake: 2.5479, D/loss_cls: 6.0393, D/loss_real: -26.6812, G/loss_fake: -1.5794, D/loss_gp: 0.3869
> torch.Size([16, 8]) torch.Size([16])
> torch.Size([16, 8]) torch.Size([16])
> torch.Size([16, 8]) torch.Size([16])
> torch.Size([16, 8]) torch.Size([16])
> torch.Size([16, 8]) torch.Size([16])
> torch.Size([16, 8]) torch.Size([16])
> torch.Size([16, 8]) torch.Size([16])
> torch.Size([16, 8]) torch.Size([16])
> torch.Size([16, 8]) torch.Size([16])
> torch.Size([16, 8]) torch.Size([16])
> Classification Acc (8 emotional expressions):  ['18.75']
> Elapsed [0:00:07.881092], Epoch [1/200], Iter [20/31], G/loss_cls: 3.8383, G/loss_rec: 0.5828, D/loss_fake: -5.0278, D/loss_cls: 9.1143, D/loss_real: -30.6130, G/loss_fake: 4.7769, D/loss_gp: 0.7379
> torch.Size([16, 8]) torch.Size([16])
> torch.Size([16, 8]) torch.Size([16])
> torch.Size([16, 8]) torch.Size([16])
> torch.Size([16, 8]) torch.Size([16])
> torch.Size([16, 8]) torch.Size([16])
> torch.Size([16, 8]) torch.Size([16])
> torch.Size([16, 8]) torch.Size([16])
> torch.Size([16, 8]) torch.Size([16])
> torch.Size([16, 8]) torch.Size([16])
> torch.Size([16, 8]) torch.Size([16])
> Classification Acc (8 emotional expressions):  ['31.25']
> Elapsed [0:00:11.084384], Epoch [1/200], Iter [30/31], G/loss_cls: 3.3109, G/loss_rec: 0.5486, D/loss_fake: 3.4921, D/loss_cls: 4.8124, D/loss_real: -38.8579, G/loss_fake: -0.7082, D/loss_gp: 0.6353
> torch.Size([8]) torch.Size([1])
> Traceback (most recent call last):
>   File "main.py", line 106, in <module>
>     main(config)
>   File "main.py", line 41, in main
>     solver.train()
>   File "/home/ramin/codes/StarGAN/solver.py", line 274, in train
>     d_loss_cls = F.cross_entropy(out_cls, real_label)
>   File "/usr/local/lib/python3.5/dist-packages/torch/nn/functional.py", line 1140, in cross_entropy
>     return nll_loss(log_softmax(input, 1), target, weight, size_average, ignore_index, reduce)
>   File "/usr/local/lib/python3.5/dist-packages/torch/nn/functional.py", line 786, in log_softmax
>     return torch._C._nn.log_softmax(input, dim)
> RuntimeError: dimension out of range (expected to be in range of [-1, 0], but got 1)

**Comment by rAm1n** [comment]
this was the easiest solution that I could find:

> 269                 if len(out_src.size()) < 3:
> 270                     out_src = out_src.unsqueeze(0)                                                                                                        
> 271                     out_cls = out_cls.unsqueeze(0)

**Comment by manishugruu** [comment]
Where should i add the following 3 lines?

**Comment by manishugruu** [comment]
Plz reply

**Comment by rAm1n** [comment]
@manishugruu I don't remember exactly and It seems the code has been updated since a year ago. I guess you should use a commit for around Jan 2018 and add these lines in solver.py. I hope this helps.

https://github.com/yunjey/stargan/blob/1a40a165f779d7f11287a6ff829ada3e306e1f49/solver.py#L268

**Comment by manishugruu** [comment]
ok

**Comment by manishugruu** [comment]
And bro,...do u have rafd dataset?

**Comment by manishugruu** [comment]
if u have it plz send methe dataset link

**Comment by rAm1n** [comment]
Please read [README.md](https://github.com/yunjey/stargan/blob/master/README.md) and follow the steps for getting datasets.

http://www.socsci.ru.nl:8180/RaFD2/RaFD?p=main

**Comment by manishugruu** [comment]
i am a student.....they dont give students the dataset?...so what can i do

**Comment by manishugruu** [comment]
cant contact the supervisor
