### ISSUE TITLE
Attribute list

### ISSUE THREAD

**Issue by amena6490** [yunjey/StarGAN#28]
Hi, I want to re-implement your work. Can you please let me know how you have created the attribute list? Is it manually or you used any code for this?

**Comment by yunjey** [comment]
@amena6490 You can check the attribute list in the second line of `list_attr_celeba.txt` file. You can download the `list_attr_celeba.txt`  by running the `bash download.sh`.

In the StarGAN code, you can add or remove attributes (or attribute values) [here](https://github.com/yunjey/StarGAN/blob/master/data_loader.py#L37
). Note that [some part of the code](https://github.com/yunjey/StarGAN/blob/master/solver.py#L167-L169) was hardcoded to cover the case of hair color (black/blond/brown). The code ensures that the target label does not have more than one hair color at the same time.


FYI, these are all available attributes: 

```
'5_o_Clock_Shadow', 'Arched_Eyebrows', 'Attractive', 'Bags_Under_Eyes', 'Bald', 'Bangs', 'Big_Lips',
'Big_Nose', 'Black_Hair', 'Blond_Hair', 'Blurry', 'Brown_Hair', 'Bushy_Eyebrows', 'Chubby',
'Double_Chin', 'Eyeglasses', 'Goatee', 'Gray_Hair', 'Heavy_Makeup', 'High_Cheekbones', 'Male',
'Mouth_Slightly_Open', 'Mustache', 'Narrow_Eyes', 'No_Beard', 'Oval_Face', 'Pale_Skin', 'Pointy_Nose',
'Receding_Hairline', 'Rosy_Cheeks', 'Sideburns', 'Smiling', 'Straight_Hair', 'Wavy_Hair', 'Wearing_Earrings',
'Wearing_Hat', 'Wearing_Lipstick', 'Wearing_Necklace', 'Wearing_Necktie', 'Young'
```
