### ISSUE TITLE
Inference issue with custom test method

### ISSUE THREAD

**Issue by petergerten** [yunjey/StarGAN#30]
Hi,

I try to write a method that allows me to do inference on one single input image and looked into the solver.test() method for that. My goal is to have a method fakeimage = process(inputimg,attributes).
From what I understand is, that I have to:
1. load the input image
2. use the torchvision transformation pipeline similar to the data_loader on the image
3. load the weights (G.load_state_dict)
4. pass image + attribute array to the network:  `fakeimg = self.G(image, target_c)`

I do not quite understand on how to setup target_c. Also I do not use a batch for inference like in the original test method but only want to pass one single image.

In step 4 I am stuck with this error:
```
/data/StarGAN/model.py in forward(self, x, c)
     56         # replicate spatially and concatenate domain information
     57         c = c.unsqueeze(2).unsqueeze(3)
---> 58         c = c.expand(c.size(0), c.size(1), x.size(2), x.size(3))
     59         x = torch.cat([x, c], dim=1)
     60         return self.main(x)

RuntimeError: invalid argument 2: dimension 3 out of range of 3D tensor at /pytorch/torch/lib/TH/generic/THTensor.c:24
```
I assume this has to do with a wrong input of "target_c".

Any suggestions on how to solve this?

Thanks!

Peter

**Comment by yunjey** [comment]
Sorry for late reply. `c` should be a tensor of shape (batch_size, c_dim). `batch_size = 1` works well.
