### ISSUE TITLE
RaFD dataset training 

### ISSUE THREAD

**Issue by wmonica** [yunjey/StarGAN#33]
When training RaFD, you said the input domain is fixed as the "neutral" expression, the target domain varies among the seven remaining expressions. 
But I have not found that the "neutral" is assigned in the training process. 
out_src, out_cls = self.D(real_x) (in solver.py line 267 )
The real_x is read through torchvision.ImageFolder. 
Could you help me? Thank you very much.

**Comment by yunjey** [comment]
@wmonica That restriction is only for comparing between StarGAN and other cross-domain models such as CycleGAN and DIAT. In StarGAN, input domain can be one of eight expressions.
