### ISSUE TITLE
Request access from RaFD

### ISSUE THREAD

**Issue by vladgaus** [yunjey/StarGAN#35]
![screenshot_5](https://user-images.githubusercontent.com/14161814/37998510-872c9050-3227-11e8-8907-95d9899ad169.png)
Greetings,
i sent request for dataset in RaFD, but steel wating approval. Can you please approve it?
P.S. My login is bengalua.
Best regards,
Vladimir.

**Comment by zhfwyy** [comment]
My request is also waiting approval.  My login is zhfwyyzjx

**Comment by jilner** [comment]
My request is also waiting approval. My login is jilner,
Can you please approve it?
Best regards,
