### ISSUE TITLE
How could I get RaFD dataset?

### ISSUE THREAD

**Issue by jinzequn** [yunjey/StarGAN#4]
Hello,

CelebA dataset is available in download.sh, but I couldn't find RaFD dataset anywhere. 

Could you offer a method to get RaFD dataset? 

Thanks a lot

**Comment by endpang** [comment]
request  for http://www.socsci.ru.nl:8180/RaFD2/RaFD?p=main

**Comment by yunjey** [comment]
@jinzequn I mentioned [here](https://github.com/yunjey/StarGAN#ii-rafd-dataset) about it . 
Because the RaFD dataset is not a public dataset, you should request access and download it manually.
