### ISSUE TITLE
rafd_crop_size?

### ISSUE THREAD

**Issue by Abhijitdas2048** [yunjey/StarGAN#40]
can anyone please let me know what is irafd_crop_size? when you tarin star gan on your dataset

**Comment by yunjey** [comment]
@Abhijitdas2048 When you train StarGAN on RaFD or your custom dataset, you can just treat `rafd_crop_size` as `crop_size`. Image processing module will center-crop images according to `crop_size`. Please see [here](https://github.com/yunjey/StarGAN/blob/master/data_loader.py#L77).

**Comment by 2110317008** [comment]
main.py: error: argument --rafd_crop_size: invalid int value: 'CROP_SIZE'

This error occurred when I was training under my own data set. I hope to get your help!
