### ISSUE TITLE
How to generate a picture with two or three attributes

### ISSUE THREAD

**Issue by theoldgun** [yunjey/StarGAN#44]
I train a model with 5 attributes:Black_Hair Blond_Hair Brown_Hair Male Young
But how can I generate a picture with two or three attributes like the paper's picture:
![image](https://user-images.githubusercontent.com/28718923/39681999-ef06bff2-51df-11e8-87f6-b100c7054688.png)

**Comment by yunjey** [comment]
The code to generate multiple attribute transfer results should be hard-coded.
You should change the code below.
 
https://github.com/yunjey/StarGAN/blob/master/solver.py#L149-L173

**Comment by quancunzuicuo** [comment]
> I train a model with 5 attributes:Black_Hair Blond_Hair Brown_Hair Male Young
> But how can I generate a picture with two or three attributes like the paper's picture:
> ![image](https://user-images.githubusercontent.com/28718923/39681999-ef06bff2-51df-11e8-87f6-b100c7054688.png)

Have you solved it?Can you share the changed solver.py?Thank you!
