### ISSUE TITLE
test problem on my own data 

### ISSUE THREAD

**Issue by theoldgun** [yunjey/StarGAN#45]
HI
thank you for share your work
I trained the celeba model,now I test the model. The test result is the mode has very good performance on training data, poor performance on my own production of data.
e.g. my test data:
![image](https://user-images.githubusercontent.com/28718923/39682649-c1d6ad90-51e3-11e8-9d9c-a9582f07eabe.png)
The generate picture has two mouthes, It is looks terrible!
Can you help me If I want to has a good performance on my data,how can I do it?
I must train my data first?

**Comment by warisha** [comment]
Please help me why it generates only one image 8 times during training samples

[
![39353773-2134ccdc-4a22-11e8-8b68-bbcfc7c3a99e](https://user-images.githubusercontent.com/18666252/45667893-4aa7bb00-bb34-11e8-80eb-577259057dac.jpg)
](url)

Test time also generate only image multiple times
1-images

Training info:
Training data: RaFD
Arranged according to your instructions
Used these configurations for train following your instructions
$ python main.py --mode train --dataset RaFD --image_size 128 --c_dim 8 
--sample_dir stargan_rafd/samples --log_dir stargan_rafd/logs 
--model_save_dir stargan_rafd/models --result_dir stargan_rafd/results

**Comment by mmiaz** [comment]
@theoldgun hi, I am currently working on the code and paper, would you mind sharing me with your own dataset?
