### ISSUE TITLE
How can I use the pre-trained models on my own images?

### ISSUE THREAD

**Issue by uxfreak** [yunjey/stargan#46]

**Comment by AidasK** [comment]
```
python main.py --mode test --dataset RaFD --rafd_crop_size 256 --image_size 256 --c_dim 5 --rafd_image_dir ../MYIMAGES/ --sample_dir stargan_custom/samples --log_dir stargan_custom/logs                  --model_save_dir stargan_celeba_256/models --result_dir stargan_custom/results
```
MYIMAGES folder has to have subfolders in it. Though results with pretrained model are no good, maybe I missed some option.
![11-images](https://user-images.githubusercontent.com/2088484/42440083-4027bfee-836d-11e8-8aa8-51cf9c9d08df.jpg)

**Comment by Tony607** [comment]
To have better result, first create a custom `list_attr_celeba_custom.txt` in folder `data/` with images listings, remember to have your custom images in `data/custom/images` to match with the names. Then run.
```bash
python main.py --mode test --dataset CelebA --image_size 256 --selected_attrs Black_Hair Blond_Hair Brown_Hair Male Young --c_dim 5 --celeba_image_dir data/custom/images --attr_path data/list_attr_celeba_custom.txt --model_save_dir stargan_celeba_256/models --result_dir stargan_celeba_256_custom/results
```
![1-images](https://user-images.githubusercontent.com/2809376/44724311-e8473600-ab04-11e8-9152-1b90abf60fa1.jpg)

**Comment by anandbhattad** [comment]
What do you mean by image listings?

**Comment by yunjey** [comment]
@AidasK Cropping input images properly will improve the visual quality of translation results. (e.g., removing black background and resizing them to 256x256)
