### ISSUE TITLE
Bad test results

### ISSUE THREAD

**Issue by theoldgun** [yunjey/StarGAN#47]
HI
thank you for share your work
I trained the celeba model,now I test the model. The test result is the mode has very good performance on training data, poor performance on my own production of data.
e.g. my test data:
/home/dms/eclipse/workspace/stargan_pytorch04/tangni/results/1-images.jpg
The generate picture has two mouthes, It is looks terrible!
Can you help me If I want to has a good performance on my data,how can I do it?

**Comment by theoldgun** [comment]
![1-images](https://user-images.githubusercontent.com/28718923/39956448-1395e8e8-5613-11e8-89f7-4fd447643c12.jpg)

**Comment by yunjey** [comment]
@theoldgun We observed that StarGAN performed quite well on test images in the CelebA dataset. However, this does not guarantee that the model works well on 'a custom image'. You may need to train StarGAN using more training images if your custom images are quite different from CelebA.
