### ISSUE TITLE
Please help me

### ISSUE THREAD

**Issue by ChengJiayao** [yunjey/StarGAN#48]
I am confused about the version of StarGAN, because when I running it on GPU, it said:
           File "/home/willamyeoh/StarGAN/solver.py", line 53, in __init__
           self.device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
           AttributeError: module 'torch' has no attribute 'device'
in the version I download to GPU, the line 53 of solver.py is: self.device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
and I found there is another version which I cloned on my own Mac is :self.dtype = torch.cuda.FloatTensor if torch.cuda.is_available() else torch.FloatTensor
Does this has anything to do with the running problem? and could you give me a hint how to solve this problem?

**Comment by yunjey** [comment]
AttributeError: module 'torch' has no attribute 'device'

For the above issue, update your PyTorch version to 0.4.0.
