### ISSUE TITLE
celeba dataset can not be downloaded

### ISSUE THREAD

**Issue by liuwei16** [yunjey/stargan#51]

**Comment by SummerHuiZhang** [comment]
Me,too.I cannot download the dataset with command 'bash download.sh celeba'.  Have you solved?
My fault was:
"--2018-06-06 18:05:32--  (try:20)  https://www.dropbox.com/s/3e5cmqgplchz85o/CelebA_nocrop.zip?dl=0
Connecting to www.dropbox.com (www.dropbox.com)|31.13.74.1|:443... failed: Connection timed out.
Giving up.

Archive:  ./data/CelebA_nocrop.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of ./data/CelebA_nocrop.zip or
        ./data/CelebA_nocrop.zip.zip, and cannot find ./data/CelebA_nocrop.zip.ZIP, period.
WARNING: timestamping does nothing in combination with -O. See the manual
for details.

--2018-06-06 18:07:41--  https://www.dropbox.com/s/auexdy98c6g7y25/list_attr_celeba.zip?dl=0
Resolving www.dropbox.com (www.dropbox.com)... 69.171.224.85
Connecting to www.dropbox.com (www.dropbox.com)|69.171.224.85|:443... failed: Connection refused.
Archive:  ./data/list_attr_celeba.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of ./data/list_attr_celeba.zip or
        ./data/list_attr_celeba.zip.zip, and cannot find ./data/list_attr_celeba.zip.ZIP, period.

**Comment by yunjey** [comment]
If you have a problem with downloading the celeb dataset using Dropbox, just use

**Comment by RosylSomai** [comment]
Just for future reference, this does not seem possible anymore due to traffic limits (notification: "Too many requests

Sorry, this link has been automatically turned off for now. Learn more about traffic limits.")
