### ISSUE TITLE
Please help me 

### ISSUE THREAD

**Issue by Gigibulid** [yunjey/StarGAN#52]
I want to use the pre-trained model for less than 5 attributes by using :

python main.py --mode test --dataset CelebA --image_size 256 --c_dim 2 \
                 --selected_attrs Blond_Hair Brown_Hair \
                 --model_save_dir='stargan_celeba_256/models' \
                 --result_dir='stargan_celeba_256/results'

but when I try it I get this:
Loading the trained models from step 200000...
Traceback (most recent call last):
  File "main.py", line 110, in <module>
    main(config)
  File "main.py", line 49, in main
    solver.test()
  File "C:\Users\gigi\PycharmProjects\StarGANPyTorch\venv\solver.py", line 526, in test
    self.restore_model(self.test_iters)
  File "C:\Users\gigi\PycharmProjects\StarGANPyTorch\venv\solver.py", line 103, in restore_model
    self.G.load_state_dict(torch.load(G_path, map_location=lambda storage, loc: storage))
  File "C:\Users\gigi\PycharmProjects\StarGANPyTorch\venv\lib\site-packages\torch\nn\modules\module.py", line 721, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for Generator:
        While copying the parameter named "main.0.weight", whose dimensions in the model are torch.Size([64, 5, 7, 7]) and whose dimensions in the checkpoint are torch.Size([64, 8, 7, 7]).

When I run the command with the 5 attributes (as you suggest in the README.md ) I do not get this error... What I could do to solve it??

**Comment by yunjey** [comment]
@Gigibulid The pretrained models were trained with 5 attributes. Therefore, the dimension of generator's first conv filter is [64, 8, 7, 7], where 8 is the sum of 3(rgb channels) and 5(attributes).  When you run the evaluation command with 2 attributes (black and blond), the dimension of generator's first conv filter is [64, 5, 7, 7]. This will cause a dimension mismatch error, when loading the trained parameters. 

For the case of 5 attributes(black, blond, brown, male, young), You can change only hair colors(black and blond) by editing [c_trg_list](https://github.com/yunjey/StarGAN/blob/master/solver.py#L543) to c_trg_list[0:2].

**Comment by Gigibulid** [comment]
Thank you sooo much!! It worked!!

If I want to change in the dataset from CelebA to my own dataset (even if that is one image) i just have to change the --dataset value?
