### ISSUE TITLE
Dimension does not match

### ISSUE THREAD

**Issue by xiaoxiongguilai** [yunjey/StarGAN#53]
python:3.6
pytorch:0.4.0
tensorflow:1.4.0

When running the following code , there is a problem:
`python main.py --mode test --dataset CelebA --image_size 128 --c_dim 5 \                                                                                    
                 --sample_dir stargan_celeba/samples --log_dir stargan_celeba/logs \
                 --model_save_dir stargan_celeba/models --result_dir stargan_celeba/results \
                 --selected_attrs Black_Hair Blond_Hair Brown_Hair Male Young`

RuntimeError: Error(s) in loading state_dict for Discriminator:
	While copying the parameter named "conv2.weight", whose dimensions in the model are torch.Size([5, 2048, 2, 2]) and whose dimensions in the checkpoint are torch.Size([5, 2048, 4, 4]).

**Comment by ssnap03** [comment]
Hey!!
I ran into the same error. How did you fix it?

**Comment by vsdivya90** [comment]
Hi @cvJonathan ,
I am facing the same issue now. Can you let me know how did you resolve this issue

**Comment by murat199** [comment]
How did you solve this problem? Please can you help me?

**Comment by murat199** [comment]
Firstly run this code; bash download.sh pretrained-celeba-128x128. And then copy the stargan_celeba_128/models/* to stargan_celeba/models/*
