### ISSUE TITLE
hasnot rafd dataset

### ISSUE THREAD

**Issue by dotsonliu** [yunjey/StarGAN#56]
i hasnot rafd dataset， Can you share your rafd data? thk you

**Comment by SummerHuiZhang** [comment]
The download.bash downloads the RaFD through dropbox, which may not work. BTW, we can download in the RaFD website.
Here is the homepage of RaFD datasets. http://www.socsci.ru.nl:8180/RaFD2/RaFD?p=main
Register and then download selected photos, they will send an E-mail to you.
