### ISSUE TITLE
Pretrained model on RaFD

### ISSUE THREAD

**Issue by leoliu37** [yunjey/stargan#59]
Your work is very interesting. Could you provide the pretrained model on RaFD about facial expression synthesis? Thanks!

**Comment by slizb** [comment]
@yunjey How to download the pre-trained RaFD model? it does not appear to be an option in the down load.sh script.

**Comment by yunjey** [comment]
It is difficult to release the pretrained model for RaFD, since the dataset is not a public. Releasing the model trained on the private dataset could be problematic

**Comment by yangyuke001** [comment]
@yunjey how about pretrained model for celeba?

**Comment by jawadtariq96** [comment]
@yangyuke001 Pretrained model for Celeba is already available. Please check the ReadMe file.

**Comment by Dashi-1997** [comment]
Could you please share the pre-trained model of CelebA and RaFD, my email is shuaiyehelaowu@163.com. Thanks!

**Comment by ShisuiUzumaki** [comment]
@yunjey  could you provide the pre-trained models for CelebA and RaFD on this email bsef17m051@pucit.edu.pk that would be a big help for personal research purpose

**Comment by MIRROR6666** [comment]
@yunjey Could you please share the pre-trained model for RaFD, my email is xyxiaoo@cqu.edu.cn. Thanks a lot!

**Comment by SonNNguyen** [comment]
@yunjey Im working on my school project could you share the pre-trained model for RaFD, my email is sonnn.m21ict@st.usth.edu.vn . Thank you very much!
