### ISSUE TITLE
If total domains are 4 #13

### ISSUE THREAD

**Issue by redhat12345** [yunjey/stargan#66]
Hi,

Thank you so much for the code and paper. My dataset contains 4 domains. The dataset structure is: trainA, trainB, trainC, trainD, testA, testB, testC, testD. How can I use this code for if 4 domains are exist in the dataset? Thanks in advanced.

**Comment by SummerHuiZhang** [comment]
As for as I know, you need to change the parameter in train bash from  '--c_dim 5' to  '--c_dim 4'.

**Comment by yunjey** [comment]
You can refer to this [instruction](
https://github.com/yunjey/StarGAN/blob/master/jpg/RaFD.m)d
