### ISSUE TITLE
Please help me to solve this

### ISSUE THREAD

**Issue by warisha** [yunjey/stargan#7]
![image](https://user-images.githubusercontent.com/18666252/33423817-bfb6a210-d5db-11e7-9de1-359089d278e2.png)

**Comment by eeric** [comment]
label value should be LongTesnsor.
if celebA was used，it should be successed. But the number of attribute: 40  that needed to add in the no.1 line.

**Comment by warisha** [comment]
i'm using Radboud dataset. I'm using pytorch first time. Can you please tell me what should i do to solve it. Thanks.

**Comment by eeric** [comment]
@warisha 
please read instructions.
https://github.com/yunjey/StarGAN/blob/master/png/RaFD.md

**Comment by warisha** [comment]
i have followed these instructions and arrange data set in the same format. 

RaFD dataset is not public.  They ask to register and then after validation they will share link with you to download dataset.

**Comment by yunjey** [comment]
@ warisha Did you solve the problem? Could you give me more information (e.g., print out the `labels` and `out` tensor)?

**Comment by warisha** [comment]
No i'm unable to understand why i'm getting this error. 
![error2](https://user-images.githubusercontent.com/18666252/33512439-6686ab5e-d752-11e7-9676-bec151889dc8.png)

**Comment by yunjey** [comment]
@warisha Please print out the data type of the tensor.  
Which version of Python do you use? 
I recommend using Python 3.6.

**Comment by warisha** [comment]
<class 'torch.FloatTensor'>
i'm using python 3.5

**Comment by Sampson-Lee** [comment]
@warisha 
Hi,  How long did it take to get a reply from Behavioural Science Institute? I requested access to RaFD dataset five days ago, but I did not receive a confirmation email so far.
