### ISSUE TITLE
Is the hair color label mutually exclusive in training?

### ISSUE THREAD

**Issue by OptimusPrimeCao** [yunjey/stargan#70]
I think in training phase, the hair color label can become (1, 1, XXXXX), that means having two hair color simultaneously. Is that matter?

**Comment by yunjey** [comment]
@OptimusPrimeCao Hair colors are mutually exclusive. We've generated target domain labels by shuffling the original domain labels. See [here](https://github.com/yunjey/stargan/blob/master/solver.py#L222-L224) for the details.
