### ISSUE TITLE
CelebA results is not so good as the paper shows

### ISSUE THREAD

**Issue by deepmo24** [yunjey/stargan#75]
Hi, 
    I use your default setting to train with attributes: Black hair, Blond hair, Eyeglasses, Mustache, Pale skin. And after 200000 iterations, I test single attribute transfer and combined attribute transfer, but I feel the combined attribute images' quality is not so good as your paper shows. The model can't fully transfer all attributes. 
![qa](https://user-images.githubusercontent.com/19352002/50321641-cf77eb80-050c-11e9-9bca-48b4db07a51a.png)

Can you explain why this happen? Or provide some suggestions about how to set  parameters to improve the quality?

**Comment by RosylSomai** [comment]
Hi,

just want to stick around because I am curious to see the response of @yunjey  (if it was a programming issue or other)

Thanks in advance.

**Comment by Ha0Tang** [comment]
How do test combined attribute transfer?

**Comment by deepmo24** [comment]
Hi, @Ha0Tang . For binary attributes, you can set the value of corresponding postion of the label  to 1. For example, if I want to combine Blond hair and Eyeglasses, the label wound be [0,1,1,0,0]. You can change the label in function `create_labels()`
