### ISSUE TITLE
Download issues and directory

### ISSUE THREAD

**Issue by RosylSomai** [yunjey/stargan#77]
Hi @yunjey ,

I hope this isn't a double question. I'm trying to run the pretrained model on a test set. I downloaded the checkpoint info and celebA images from the github of Junho Kim (@taki0112) but I can't seem to get the structure of my directory right, because I downloaded the CelebA folder from the official website.

Could you please provide me with the structure of the folder (particularly the data-folders and checkpoint info, but preferably the entire folderstructure) and include some information on the size of the images that are supposed to be in there (I now have the 178x218 images).

Many thanks in advance

**Comment by RosylSomai** [comment]
I ended up downloading it from the official site, but through the google drive link (under "news"):
http://mmlab.ie.cuhk.edu.hk/projects/CelebA.html
(so without download.sh)

**Comment by yunjey** [comment]
@RosylSomai @DongHwanJang Sorry for late reply. I fixed the download link. Now, you can download the celeba images and labels using `bash download.sh celeba`.
