### ISSUE TITLE
How to continue the interrupted training?

### ISSUE THREAD

**Issue by chikiuso** [yunjey/StarGAN#9]
Hello, I started the training and the computer shutdown by accident, is there anyway I could continue the interrupted training? Doesn't have to start it over again? thanks.

**Comment by yunjey** [comment]
@chikiuso You can resume the training by using an argument `pretrained_model `. Below is an example of a command that resumes when the training is interrupted in 2 epoch 1000 iterations.

```
python main.py --mode='train' --pretrained_model=2_1000 --dataset='CelebA' --c_dim=5 --image_size=128 \
                 --sample_path='stargan_celebA/samples' --log_path='stargan_celebA/logs' \
                 --model_save_path='stargan_celebA/models' --result_path='stargan_celebA/results'
```
