### ISSUE TITLE
Is this project available with multi gpus (more than 1)?

### ISSUE THREAD

**Issue by wangguanan** [yunjey/stargan#90]
When I run the code with multi gpus (more than 1), the loss cannot converge.
How can I solve it?

**Comment by XHChen0528** [comment]
It is an bug of pytorch, i meet this problem those day.
I fixed it by updating the pytorch version from 1.1 to 1.2.
I suggest you try to upgrade your pytorch.

**Comment by wangguanan** [comment]
got it, thanks.
I will have a try.
